version: '3.8'
services:
  postgres:
    image: postgres:9
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
  web:
    build: ./
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    environment:
      BINDING: 0.0.0.0
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/
      PORT: 5000
      REDIS_URL: redis://redis:6379/docker-compose
    restart: always
volumes:
  pg-data:
